# Generated by Django 5.2.8 on 2025-11-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElShop', '0002_auto_20251109_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
