# Generated by Django 5.2.8 on 2025-11-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElShop', '0006_seed_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('card', 'Card'), ('transfer', 'Transfer'), ('mir', 'MIR'), ('cash', 'Cash')], max_length=20),
        ),
    ]
