# Generated by Django 5.2.8 on 2025-11-11 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ElShop', '0007_alter_payment_method'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('customer', 'is_default')},
        ),
        migrations.RemoveField(
            model_name='address',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='address',
            name='type',
        ),
    ]
