# Generated by Django 5.2.8 on 2025-11-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElShop', '0009_alter_address_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(default='₽', max_length=3),
        ),
    ]
