# Generated by Django 5.2.8 on 2025-11-11 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ElShop', '0010_alter_order_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='weight_kg',
        ),
    ]
