# Generated by Django 5.2.13 on 2026-04-09 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ElShop', '0011_remove_product_weight_kg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='line1',
        ),
        migrations.RemoveField(
            model_name='address',
            name='line2',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
    ]
